import React, { useState, useRef, useEffect } from 'react';
import {
  Box,
  Button,
  VStack,
  HStack,
  Text,
  Input,
  IconButton,
  Avatar,
  Flex,
  Link,
  Image,
} from '@chakra-ui/react';
import { FiMessageCircle, FiX, FiSend } from 'react-icons/fi';

interface Message {
  role: 'user' | 'assistant';
  content: string;
  properties?: Property[];
}

interface Property {
  id: string;
  title: string;
  propertyType: string;
  price: number;
  city: string;
  address: string;
  image: string | null;
  sellingType: string;
  bhk: number | null;
  baths: number | null;
  areaSize: number | null;
  areaUnit: string | null;
}

const Chatbot: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    {
      role: 'assistant',
      content: 'Hello! I\'m your property assistant. I can help you find the perfect property. What are you looking for?',
    },
  ]);
  const [inputMessage, setInputMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  useEffect(() => {
    if (isOpen && inputRef.current) {
      inputRef.current.focus();
    }
  }, [isOpen]);

  const handleSendMessage = async () => {
    if (!inputMessage.trim() || isLoading) return;

    const userMessage = inputMessage.trim();
    setInputMessage('');
    setMessages((prev) => [...prev, { role: 'user', content: userMessage }]);
    setIsLoading(true);

    try {
      const response = await fetch('/api/chatbot', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          message: userMessage,
          conversationHistory: messages.map((m) => ({
            role: m.role,
            content: m.content,
          })),
        }),
      });

      const data = await response.json();

      if (response.ok && data.message) {
        // Log Gemini status for debugging (only in development)
        if (process.env.NODE_ENV === 'development' && data._meta) {
          if (data._meta.usingGemini) {
            console.log('✅ Gemini is working! Response generated by Gemini');
          } else {
            console.log('⚠️ Using fallback (Gemini not available):', data._meta.geminiError || 'Unknown error');
          }
        }

        setMessages((prev) => [
          ...prev,
          {
            role: 'assistant',
            content: data.message,
            properties: data.properties || [],
          },
        ]);
      } else {
        // Better error handling
        const errorMessage = data.message || data.error || 'Sorry, I encountered an error. Please try again.';
        console.error('Chatbot API error:', data);
        setMessages((prev) => [
          ...prev,
          {
            role: 'assistant',
            content: errorMessage,
          },
        ]);
      }
    } catch (error: any) {
      console.error('Chat error:', error);
      setMessages((prev) => [
        ...prev,
        {
          role: 'assistant',
          content: `Sorry, I'm having trouble connecting. ${error.message ? `Error: ${error.message}` : 'Please check your internet connection and try again.'}`,
        },
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  return (
    <>
      {/* Chat Button */}
      {!isOpen && (
        <Box
          position="fixed"
          bottom={{ base: '16px', md: '24px' }}
          right={{ base: '16px', md: '24px' }}
          zIndex={1000}
        >
          <Box
            as="button"
            onClick={() => setIsOpen(true)}
            borderRadius="full"
            px={{ base: 3, md: 6 }}
            py={{ base: 3, md: 6 }}
            fontSize={{ base: 'xs', md: 'md' }}
            fontWeight="600"
            color="white"
            bg="rgba(59, 130, 246, 0.9)"
            border="1px solid"
            borderColor="rgba(255, 255, 255, 0.18)"
            boxShadow="0 8px 32px 0 rgba(31, 38, 135, 0.37)"
            cursor="pointer"
            display="flex"
            alignItems="center"
            gap={{ base: 1.5, md: 2 }}
            transition="all 0.3s ease"
            _hover={{
              bg: 'rgba(37, 99, 235, 0.95)',
              transform: 'scale(1.05)',
              boxShadow: '0 12px 40px 0 rgba(31, 38, 135, 0.5)',
            }}
            _active={{
              transform: 'scale(0.95)',
            }}
            sx={{
              backdropFilter: 'blur(10px)',
              WebkitBackdropFilter: 'blur(10px)',
            }}
          >
            <FiMessageCircle style={{ fontSize: 'clamp(16px, 4vw, 20px)' }} />
            <Text as="span" display={{ base: 'none', sm: 'inline' }}>
              Chat with us
            </Text>
          </Box>
        </Box>
      )}

      {/* Chat Window */}
      {isOpen && (
        <Box
          position="fixed"
          bottom="24px"
          right="24px"
          width={{ base: 'calc(100vw - 48px)', md: '400px' }}
          height={{ base: 'calc(100vh - 48px)', md: '600px' }}
          maxHeight="600px"
          bg="rgba(255, 255, 255, 0.25)"
          borderRadius="xl"
          boxShadow="0 8px 32px 0 rgba(31, 38, 135, 0.37)"
          zIndex={1001}
          display="flex"
          flexDirection="column"
          border="1px solid"
          borderColor="rgba(255, 255, 255, 0.18)"
          overflow="hidden"
          sx={{
            backdropFilter: 'blur(20px) saturate(180%)',
            WebkitBackdropFilter: 'blur(20px) saturate(180%)',
          }}
        >
          {/* Header */}
          <Flex
            justify="space-between"
            align="center"
            px={4}
            py={3}
            bg="rgba(59, 130, 246, 0.7)"
            color="white"
            borderRadius="xl 0 0 0"
            borderBottom="1px solid"
            borderColor="rgba(255, 255, 255, 0.2)"
            sx={{
              backdropFilter: 'blur(10px)',
              WebkitBackdropFilter: 'blur(10px)',
            }}
          >
            <HStack spacing={2}>
              <Avatar size="sm" bg="blue.400" />
              <VStack spacing={0} align="start">
                <Text fontSize="sm" fontWeight="600">
                  Property Assistant
                </Text>
                <Text fontSize="xs" opacity={0.9}>
                  Online
                </Text>
              </VStack>
            </HStack>
            <HStack spacing={2}>
              <IconButton
                aria-label="Close chat"
                icon={<FiX />}
                size="sm"
                variant="ghost"
                color="white"
                _hover={{ bg: 'blue.600' }}
                onClick={() => setIsOpen(false)}
              />
            </HStack>
          </Flex>

          {/* Messages */}
          <Box
            flex="1"
            overflowY="auto"
            p={4}
            bg="rgba(249, 250, 251, 0.3)"
            sx={{
              backdropFilter: 'blur(5px)',
              WebkitBackdropFilter: 'blur(5px)',
              '&::-webkit-scrollbar': {
                width: '6px',
              },
              '&::-webkit-scrollbar-track': {
                background: 'rgba(255, 255, 255, 0.1)',
                borderRadius: '10px',
              },
              '&::-webkit-scrollbar-thumb': {
                background: 'rgba(59, 130, 246, 0.3)',
                borderRadius: '10px',
                '&:hover': {
                  background: 'rgba(59, 130, 246, 0.5)',
                },
              },
            }}
          >
            <VStack spacing={4} align="stretch">
              {messages.map((msg, idx) => (
                <Box key={idx}>
                  <Flex
                    justify={msg.role === 'user' ? 'flex-end' : 'flex-start'}
                    mb={2}
                  >
                    <Box
                      maxW="80%"
                      px={4}
                      py={2}
                      borderRadius="xl"
                      bg={msg.role === 'user' 
                        ? 'rgba(59, 130, 246, 0.8)' 
                        : 'rgba(255, 255, 255, 0.6)'}
                      color={msg.role === 'user' ? 'white' : 'gray.800'}
                      boxShadow="0 4px 16px 0 rgba(31, 38, 135, 0.2)"
                      border="1px solid"
                      borderColor={msg.role === 'user' 
                        ? 'rgba(255, 255, 255, 0.3)' 
                        : 'rgba(255, 255, 255, 0.4)'}
                      sx={{
                        backdropFilter: 'blur(10px)',
                        WebkitBackdropFilter: 'blur(10px)',
                      }}
                    >
                      <Text fontSize="sm" whiteSpace="pre-wrap">
                        {msg.content}
                      </Text>
                    </Box>
                  </Flex>

                  {/* Property Suggestions */}
                  {msg.properties && msg.properties.length > 0 && (
                    <VStack spacing={2} align="stretch" mt={2}>
                      {msg.properties.map((property) => (
                        <Link
                          key={property.id}
                          href={`/properties/${property.id}`}
                          _hover={{ textDecoration: 'none' }}
                        >
                          <Box
                            p={3}
                            bg="rgba(255, 255, 255, 0.7)"
                            borderRadius="xl"
                            border="1px solid"
                            borderColor="rgba(255, 255, 255, 0.4)"
                            boxShadow="0 4px 16px 0 rgba(31, 38, 135, 0.15)"
                            _hover={{
                              borderColor: 'rgba(59, 130, 246, 0.5)',
                              boxShadow: '0 8px 24px 0 rgba(59, 130, 246, 0.3)',
                              transform: 'translateY(-2px)',
                              bg: 'rgba(255, 255, 255, 0.85)',
                            }}
                            transition="all 0.3s ease"
                            sx={{
                              backdropFilter: 'blur(10px)',
                              WebkitBackdropFilter: 'blur(10px)',
                            }}
                          >
                            <HStack spacing={3} align="start">
                              {property.image && (
                                <Image
                                  src={property.image}
                                  alt={property.title}
                                  boxSize="60px"
                                  objectFit="cover"
                                  borderRadius="md"
                                  fallbackSrc="https://placehold.co/60x60/e2e8f0/64748b?text=Property"
                                />
                              )}
                              <VStack spacing={1} align="start" flex="1">
                                <Text fontSize="sm" fontWeight="600" noOfLines={1}>
                                  {property.title}
                                </Text>
                                <Text fontSize="xs" color="gray.600">
                                  {property.propertyType} • {property.city}
                                </Text>
                                <Text fontSize="xs" fontWeight="600" color="blue.600">
                                  ₹{property.price?.toLocaleString('en-IN') || 'Price on request'}
                                </Text>
                              </VStack>
                            </HStack>
                          </Box>
                        </Link>
                      ))}
                    </VStack>
                  )}

                  {isLoading && idx === messages.length - 1 && (
                    <HStack spacing={1} mt={2}>
                      <Box
                        w="8px"
                        h="8px"
                        bg="gray.400"
                        borderRadius="full"
                        animation="bounce 1.4s infinite"
                      />
                      <Box
                        w="8px"
                        h="8px"
                        bg="gray.400"
                        borderRadius="full"
                        animation="bounce 1.4s infinite 0.2s"
                      />
                      <Box
                        w="8px"
                        h="8px"
                        bg="gray.400"
                        borderRadius="full"
                        animation="bounce 1.4s infinite 0.4s"
                      />
                    </HStack>
                  )}
                </Box>
              ))}
              <div ref={messagesEndRef} />
            </VStack>
          </Box>

          {/* Input */}
          <Box
            p={3}
            bg="rgba(255, 255, 255, 0.4)"
            borderTop="1px solid"
            borderColor="rgba(255, 255, 255, 0.2)"
            borderRadius="0 0 xl xl"
            sx={{
              backdropFilter: 'blur(10px)',
              WebkitBackdropFilter: 'blur(10px)',
            }}
          >
            <HStack spacing={2}>
              <Input
                ref={inputRef}
                value={inputMessage}
                onChange={(e) => setInputMessage(e.target.value)}
                onKeyPress={handleKeyPress}
                placeholder="Type your message..."
                size="md"
                borderRadius="xl"
                bg="rgba(255, 255, 255, 0.6)"
                borderColor="rgba(255, 255, 255, 0.3)"
                _focus={{
                  borderColor: 'rgba(59, 130, 246, 0.6)',
                  boxShadow: '0 0 0 2px rgba(59, 130, 246, 0.2)',
                  bg: 'rgba(255, 255, 255, 0.8)',
                }}
                _hover={{
                  borderColor: 'rgba(255, 255, 255, 0.5)',
                }}
                disabled={isLoading}
                sx={{
                  backdropFilter: 'blur(5px)',
                  WebkitBackdropFilter: 'blur(5px)',
                }}
              />
              <IconButton
                aria-label="Send message"
                icon={<FiSend />}
                onClick={handleSendMessage}
                disabled={!inputMessage.trim() || isLoading}
                bg="rgba(59, 130, 246, 0.8)"
                color="white"
                border="1px solid"
                borderColor="rgba(255, 255, 255, 0.2)"
                boxShadow="0 4px 12px 0 rgba(59, 130, 246, 0.3)"
                _hover={{ 
                  bg: 'rgba(37, 99, 235, 0.9)',
                  boxShadow: '0 6px 16px 0 rgba(59, 130, 246, 0.4)',
                  transform: 'scale(1.05)',
                }}
                _active={{
                  transform: 'scale(0.95)',
                }}
                _disabled={{
                  bg: 'rgba(156, 163, 175, 0.5)',
                  cursor: 'not-allowed',
                  opacity: 0.6,
                }}
                transition="all 0.2s ease"
                sx={{
                  backdropFilter: 'blur(10px)',
                  WebkitBackdropFilter: 'blur(10px)',
                }}
              />
            </HStack>
          </Box>
        </Box>
      )}

      <style jsx>{`
        @keyframes bounce {
          0%, 80%, 100% {
            transform: scale(0);
          }
          40% {
            transform: scale(1);
          }
        }
      `}</style>
    </>
  );
};

export default Chatbot;

