export const partners = [
  'L&T Realty',
  'Sobha Developers',
  'Prestige Group',
  'Godrej Properties',
  'Tata Housing',
  'DLF',
  'M3M India',
  'Mangalya Developers',
  'Confident Group',
  'Unity Group',
  'Puravankara',
  'Brigade Group',
  'Shapoorji Pallonji',
  'Kalyan Developers',
  'Lodha Group',
  'Raheja Developers',
  'Mahindra Lifespaces',
  'Kolte Patil',
  'Sunteck Realty',
  'Piramal Realty',
];
